
package it.ginopc.soap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateService", targetNamespace = "http://server.soap.ginopc.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArea", targetNamespace = "http://server.soap.ginopc.it/", className = "it.ginopc.soap.ws.GetArea")
    @ResponseWrapper(localName = "getAreaResponse", targetNamespace = "http://server.soap.ginopc.it/", className = "it.ginopc.soap.ws.GetAreaResponse")
    @Action(input = "http://server.soap.ginopc.it/CalculateService/getAreaRequest", output = "http://server.soap.ginopc.it/CalculateService/getAreaResponse")
    public Double getArea(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCirconferenza", targetNamespace = "http://server.soap.ginopc.it/", className = "it.ginopc.soap.ws.GetCirconferenza")
    @ResponseWrapper(localName = "getCirconferenzaResponse", targetNamespace = "http://server.soap.ginopc.it/", className = "it.ginopc.soap.ws.GetCirconferenzaResponse")
    @Action(input = "http://server.soap.ginopc.it/CalculateService/getCirconferenzaRequest", output = "http://server.soap.ginopc.it/CalculateService/getCirconferenzaResponse")
    public Double getCirconferenza(
        @WebParam(name = "arg0", targetNamespace = "")
        Double arg0);

}
