
package it.ginopc.soap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateServiceImplService", targetNamespace = "http://server.soap.ginopc.it/", wsdlLocation = "http://localhost:8080/ws/calculate?wsdl")
public class CalculateServiceImplService
    extends Service
{

    private final static URL CALCULATESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATESERVICEIMPLSERVICE_QNAME = new QName("http://server.soap.ginopc.it/", "CalculateServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/calculate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CalculateServiceImplService() {
        super(__getWsdlLocation(), CALCULATESERVICEIMPLSERVICE_QNAME);
    }

    public CalculateServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATESERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculateServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATESERVICEIMPLSERVICE_QNAME);
    }

    public CalculateServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATESERVICEIMPLSERVICE_QNAME, features);
    }

    public CalculateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateService
     */
    @WebEndpoint(name = "CalculateServiceImplPort")
    public CalculateService getCalculateServiceImplPort() {
        return super.getPort(new QName("http://server.soap.ginopc.it/", "CalculateServiceImplPort"), CalculateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateService
     */
    @WebEndpoint(name = "CalculateServiceImplPort")
    public CalculateService getCalculateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.ginopc.it/", "CalculateServiceImplPort"), CalculateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATESERVICEIMPLSERVICE_EXCEPTION;
        }
        return CALCULATESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
